### ISSUE TITLE
Semaphore docker container failing to build

### ISSUE THREAD

**Issue by marissaeinhorn** [dev4vater/vater#298]
Running `vater restart -s semaphore` on a new install results in failure

**Comment by marissaeinhorn** [comment]
Possible solution: 
https://stackoverflow.com/questions/59471545/when-trying-to-build-docker-image-i-get-gcc-executable-file-not-found-in-p

**Comment by marissaeinhorn** [comment]
Ran `apt-get install build-essential`  ubuntu said it was already latest version

**Comment by marissaeinhorn** [comment]
Trying `export CGO_ENABLED=0`  Was previously set to 1

**Comment by Donovan-Medina** [comment]
1. Solved issue with go `command not found`
Instead of trying to install go manually and editing the profile paths we can install `go` using ubuntu's snap package manager.
I decided to use the channel 1.19/stable and that works. Updating control-services/bin/install_requirements.sh

2. The second issue is with the repo go-task. It no longer has a [branch ](https://github.com/go-task/task/branches)`v3` so it doesn't install the module. Checking which module to use instead and will update control-services/cli/semaphore.py

**Comment by Donovan-Medina** [comment]
Running the subprocess command manually prompts this error:
![image](https://user-images.githubusercontent.com/36013253/199337250-de8440cc-69b6-4f62-83e5-fb85037262f0.png)
![image](https://user-images.githubusercontent.com/36013253/199337338-38623c12-7b89-4223-ac7a-b61a9e492e9e.png)
![image](https://user-images.githubusercontent.com/36013253/199337406-bb89d982-1e7a-453a-be0f-09801d152eea.png)

**Comment by Donovan-Medina** [comment]
Looking at the Docker file from the cherrypick branch we are using from rmfirth/semaphore:
![image](https://user-images.githubusercontent.com/36013253/199513798-20716596-d696-4480-bca4-477a4fc513ee.png)
There might be a dependency that is missing/broken not allowing golang to use gcc when building the container.
I'll add `build-base` to `RUN apk add ...` to ensure it installs gcc for the container to use. I'll report my findings, but if this is indeed where its breaking -- then we'll have to move to a more updated branch of rmfirth/semaphore

**Comment by Donovan-Medina** [comment]
After adding `build-base` to `Run apk add ...` on the cherrypick rmfrith/semaphore/deployment/docker/prod/Dockerfile it successfully builds. I am assuming there are issues with `FROM frolvlad/alpine-glibc:alpine-3.13` not being compatible with the newer version of docker. 
![image](https://user-images.githubusercontent.com/36013253/199526773-8332fc58-9aa7-4cec-94b8-5e6477fef566.png)
Looking into using a newer branch version of rmfirth/semaphore

**Comment by Donovan-Medina** [comment]
Went ahead with adding a subprocess in semaphore.py to add the `build-base` in rmfirth/semaphore Dockerfile. This ensures gcc is part of the image and can be used. Semaphore now builds successfully.

**Comment by marissaeinhorn** [comment]
Getting a task not found error - taking a look at the go path install again

```
Traceback (most recent call last):
  File "/home/control/vater/control-services/cli/vater.py", line 158, in <module>
    main()
  File "/home/control/vater/control-services/cli/vater.py", line 25, in main
    restart(c, p.args)
  File "/home/control/vater/control-services/cli/vater.py", line 94, in restart
    s.restartContainer()
  File "/home/control/vater/control-services/cli/semaphore.py", line 286, in restartContainer
    self.buildSemaphore()
  File "/home/control/vater/control-services/cli/semaphore.py", line 94, in buildSemaphore
    subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'task'
```

**Comment by marissaeinhorn** [comment]
Control/sudos path needs to include /usr/local/go/bin for task to be found.  Will modify setup scripts
